Controllers/ClientesController.cs
using PrVeterinaria.Libs;
using PrVeterinaria.Models;
using PrVeterinaria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PrVeterinaria.Controllers
{
    public class ClientesController : Controller
    {
        DBContexto _db = new DBContexto();
        // GET: Usuarios
        #region Clientes
        [Authentication("CLIENTES")]
        public ActionResult Index()
        {
            var clientes = _db.Clientes.Select(client =>
                       new listaClientes
                       {
                           id_Cliente = client.id_Cliente,
                           nombre = client.nombreCliente,
                           email = client.correo,
                           ciudad = client.ciudad,
                           telefono = client.telefono,
                           tipoDocumento = client.TipoDocumento.descripcion,
                           numeroDocumento = client.numeroDocumento
                       }).ToList();

            ViewBag.listaClientes = clientes;
            return View();
        }

        [Authentication("CLIENTES")]
        public ActionResult Create()
        {
            ViewBag.TipoDoc = new SelectList(_db.TipoDocumento, "id_tipoDocumento", "descripcion");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Nuevo nuevo)
        {
            Clientes NewUser = new Clientes();
            NewUser.ciudad = nuevo.ciudad;
            NewUser.correo = nuevo.email;
            NewUser.telefono = nuevo.telefono;
            NewUser.numeroDocumento = nuevo.numeroDocumento;
            NewUser.id_tipoDocumento = nuevo.tipoDoc;
            NewUser.nombreCliente = nuevo.nombre;

            _db.Clientes.Add(NewUser);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authentication("CLIENTES")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clientes editUser = _db.Clientes.Find(id);

            ViewBag.TipoDoc = new SelectList(_db.TipoDocumento, "id_tipoDocumento", "descripcion");
            return View(editUser);
        }

        [HttpPost]
        public ActionResult Edit(Clientes edit)
        {
            Clientes tblUsuario = _db.Clientes.Find(edit.id_Cliente);
            tblUsuario.correo = edit.correo;
            tblUsuario.ciudad = edit.ciudad;
            tblUsuario.telefono = edit.telefono;

            _db.Entry(tblUsuario).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Edit", new { id = edit.id_Cliente });
        }
        #endregion

        #region Mascotas
        [Authentication("CLIENTES")]
        public ActionResult IndexMascota()
        {
           var Mascotas = _db.Mascota.Select(m =>
           new MascotaDTO
           {
               id_mascota=m.id_mascota,
               dueño = m.Clientes.nombreCliente,
               nombreMascota = m.nombreMascota,
               fecha_nacimiento_mascota = m.fecha_nacimiento_mascota,
               edad = m.edad,
               raza = m.raza,
               especie = m.TipoMascota.nombre
           }).ToList();

            ViewBag.listaMascotas = Mascotas;
            return View();
        }

        [Authentication("CLIENTES")]
        public ActionResult CreateMascota()
        {
            ViewBag.especie = new SelectList(_db.TipoMascota, "id_tipoMascota", "nombre");
            ViewBag.cliente = new SelectList(_db.Clientes, "id_Cliente", "nombreCliente");
            return View();
        }

        [HttpPost]
        public ActionResult CreateMascota(Mascota mascota)
        {
            _db.Mascota.Add(mascota);
            _db.SaveChanges();

            return RedirectToAction("IndexMascota");
        }

        [Authentication("CLIENTES")]
        public ActionResult HistorialMascota(int? id)
        {

            DetalleMascota historialClinica = new DetalleMascota();

            historialClinica.id_mascota = id ?? 0;
            var Historial = _db.DetalleMascota.Where(x => x.id_mascota == historialClinica.id_mascota).Select(p =>
                       new DetalleMascotaDTO
                       {
                           id_detalleMascota = p.id_detalleMascota,
                           nombreDetalle = p.nombreDetalle,
                           fecha = p.fecha                        
                       });

            ViewBag.historial = Historial.ToList();
            return View(historialClinica);
        }

        [HttpPost]
        public ActionResult HistorialMascota(DetalleMascota detalle)
        {
            _db.DetalleMascota.Add(detalle);
            _db.SaveChanges();

            return RedirectToAction("HistorialMascota", new { id = detalle.id_mascota});

        }
        #endregion
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ReporteController.cs
using PrVeterinaria.Libs;
using PrVeterinaria.Models;
using PrVeterinaria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WinForms;


namespace PrVeterinaria.Controllers
{
    public class ReporteController : Controller
    {

        DBContexto _db = new DBContexto();
        [Authentication("VENTAS")]
        public ActionResult Index()
        {
            return View();
        }

        [Authentication("VENTAS")]
        public ActionResult Create()
        {
            ViewBag.cliente = new SelectList(_db.Clientes, "id_Cliente", "nombreCliente");
            ViewBag.tipoPago = new SelectList(_db.TipoPago, "id_tipoPago", "nombre");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Factura factura)
        {
            factura.fecha = DateTime.Now;

            _db.Factura.Add(factura);
            _db.SaveChanges();
            return RedirectToAction("DetalleVenta", new { id = factura.id_factura });
        }

        [Authentication("VENTAS")]
        public ActionResult DetalleVenta(int id)
        {
            try
            {

                Factura detalleFactura = _db.Factura.FirstOrDefault(p => p.id_factura == id);

                VentaViewModel venta = new VentaViewModel();

                venta.id_factura = detalleFactura.id_factura;
                venta.id_Cliente = detalleFactura.Clientes.numeroDocumento;
                venta.id_tipoPago = detalleFactura.TipoPago.nombre;

                ViewBag.Producto = _db.Producto.Select(x => new SelectListItem { Value = x.id_producto.ToString(), Text = x.nombre + " - " + x.precio });

                var detalle = _db.DetalleFactura.Where(x => x.id_factura == id).Select(m =>
                  new VentaViewModel
                  {
                      id_producto = m.id_producto,
                      id_Cliente = m.Factura.Clientes.nombreCliente,
                      id_tipoPago = m.Factura.TipoPago.nombre,
                      cantidad = m.cantidad,
                      producto = m.Producto.nombre,
                      precio = m.precio
                  }).ToList();

                ViewBag.listaMascotas = detalle;

                return View(venta);
            }
            catch (Exception e)
            {
                return RedirectToAction("Create");
            }
        }

        [HttpPost]
        public ActionResult DetalleVenta(VentaViewModel venta)
        {
            DetalleFactura detalle = new DetalleFactura();

            detalle.id_factura = venta.id_factura;
            detalle.id_producto = venta.id_producto;
            detalle.cantidad = venta.cantidad;
            detalle.precio = _db.Producto.FirstOrDefault(x => x.id_producto == venta.id_producto).precio;


            _db.DetalleFactura.Add(detalle);
            _db.SaveChanges();
            return RedirectToAction("DetalleVenta", new { id = detalle.id_factura });
        }

        [Authentication("CONSULTA")]
        public ActionResult Factura(int id)
        {

            
            LocalReport localReport = new LocalReport();
            string path = Server.MapPath("~/Reportes/Facturas/Factura.rdlc");

            if (System.IO.File.Exists(path))
            {
                localReport.ReportPath = path;
            }
            else
            {
                return RedirectToAction("DetalleVenta", new { id = id });
            }

            var TotalFactura = _db.DetalleFactura.Where(x => x.id_factura == id).ToList();
            decimal total = 0;
            foreach(var i in TotalFactura)
            {
                total += i.precio;
            }
  
            List<VentaReporte> CertificadoVenta = (
                                                    from b in _db.Factura
                                                    join p in _db.DetalleFactura on b.id_factura equals p.id_factura
                                                    join a in _db.Producto on p.id_producto equals a.id_producto
                                                    join r in _db.Clientes on b.id_Cliente equals r.id_Cliente
                                                    where b.id_factura == id
                                                    select new VentaReporte
                                                    {
                                                        id_factura = b.id_factura,
                                                        precio = p.precio,
                                                        articulo = a.nombre,
                                                        fecha = DateTime.Now,
                                                        tipoPago=b.TipoPago.nombre,
                                                        Direccion=r.direccion,
                                                        cantidad = p.cantidad,
                                                        nombreCliente = r.nombreCliente,
                                                        ciudad = r.ciudad,
                                                        TipoDocumento=r.TipoDocumento.descripcion,
                                                        numeroDocumento=r.numeroDocumento,
                                                        Total= p.precio * p.cantidad,
                                                        TotalFactura=total
                                                    }).ToList();


            ReportDataSource certificado = new ReportDataSource("Factura", CertificadoVenta);

            localReport.DataSources.Add(certificado);
            string reportType = "PDF";
            string mimeType;
            string encoding;
            string fileNameExtension;

            string deviceInfo =

            "<DeviceInfo>" +
            "  <OutputFormat>" + reportType + "</OutputFormat>" +
             "  <PageWidth>22,59cm</PageWidth>" +
             "  <PageHeight>29,94cm</PageHeight>" +
             "  <MarginTop>0,00001cm </MarginTop>" +
             "  <MarginLeft>0,00001cm</MarginLeft>" +
             "  <MarginRight>0,00001cm</MarginRight>" +
             "  <MarginBottom>0,00001cm</MarginBottom>" +
            "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;


            renderedBytes = localReport.Render(
            reportType,
            deviceInfo,
                        out mimeType,
                        out encoding,
                        out fileNameExtension,
                        out streams,
                        out warnings);

            return File(renderedBytes, mimeType);
        }

        [Authentication("CONSULTA")]
        public ActionResult ReporteVentas()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ReporteVentas([Bind(Include = "fechaInicial,fechaFinal")] ViewReporteFecha datos)
        {
            if (ModelState.IsValid)
            {
                LocalReport localReport = new LocalReport();
                string path = Server.MapPath("~/Reportes/Facturas/ReporteFecha.rdlc");
                if (!System.IO.File.Exists(path))
                {
                    return RedirectToAction("");
                }
                localReport.ReportPath = path;

                var consulta = (from b in _db.Factura
                                join p in _db.DetalleFactura on b.id_factura equals p.id_factura
                                join a in _db.Producto on p.id_producto equals a.id_producto
                                where b.fecha >= datos.fechaInicial && b.fecha <= datos.fechaFinal
                                select new VentaReporte
                                {
                                    id_factura = b.id_factura,
                                    precio = p.precio,
                                    nombreCliente = a.id_tipoProducto.ToString(),
                                    articulo = a.nombre,
                                    fecha = b.fecha,
                                    tipoPago = b.TipoPago.nombre,
                                    cantidad = p.cantidad,
                                    Total = p.precio * p.cantidad
                                }).ToList();

                localReport.DataSources.Add(new ReportDataSource("ReporteFecha", consulta));

                string reportType = "EXCELOPENXML";
                string mimeType;
                string encoding;
                string fileNameExtension;

                string deviceInfo =
                    "<DeviceInfo>" +
                    "  <OutputFormat>" + reportType + "</OutputFormat>" +
                     "  <PageWidth>11in</PageWidth>" +
                     "  <PageHeight>8.5in</PageHeight>" +
                     "  <MarginTop>0.5in</MarginTop>" +
                     "  <MarginLeft>1in</MarginLeft>" +
                     "  <MarginRight>1in</MarginRight>" +
                     "  <MarginBottom>0.5in</MarginBottom>" +
                    "</DeviceInfo>";

                Warning[] warnings;
                string[] streams;
                byte[] renderedBytes;

                renderedBytes = localReport.Render(
                reportType,
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtension,
                out streams,
                out warnings);

                return File(renderedBytes, mimeType);

            }
               return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Footer.cshtml
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Acme <span class="hidden-xs"> - Universida Del Valle <span class="hidden-xs"> - Calvos++</span> © 2021</span>
        </div>
       
    </div>
</div>

Views/Shared/_Header.cshtml
<header id="header">
    <!-- Logo -->

    <div id="logo-group">
        <span id="logo"> <img src="~/Content/images/logo.jpeg" alt="Logo"> </span>


    </div>
    <div class="pull-right px-2">
        <div class="project-context hidden-xs">
            <span class="label">Usuario:</span>
            <span class="project-selector dropdown-toggle" data-toggle="dropdown">@User.Identity.Name.Split('@')[1] <i class="fa fa-angle-down"></i></span>
            <ul class="dropdown-menu">
                <li>
                  <a href="@Url.Action("CambiarPassword", "Usuarios", new { area = "" })" class="padding-7 padding-top-0 padding-bottom-0"><i class="fa fa-key"></i> Cambiar Contraseña</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Logout", "Home", new { area = "" })" class="padding-10 padding-top-5 padding-bottom-5"><i class="fa fa-power-off"></i> <strong><u>S</u>alir</strong></a>
                </li>
            </ul>
        </div>

        <div id="hide-menu" class="btn-header pull-right hidden-lg hidden-md">
            <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>

        <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
            <li class="">
                <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                    <div class="btn btn-default">@*User.Identity.Name*@ <i class="fa fa-chevron-down"></i></div>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="@Url.Action("CambiarPassword","Usuarios")" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-key"></i> Cambiar Password</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("LogOut","Home", new { area = "" })" class="padding-10 padding-top-5 padding-bottom-5"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Acme -  Universidad Del Valle</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/platillaSmartAdmin")
    @Styles.Render("~/Content/Site.css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="smart-style-2">
    @if (Request.IsAuthenticated)
    {
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_Header")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_TopMenu")
    }
 
    <div id="main" role="main">
        <div id="content">
            @RenderBody()
        </div>
    </div>

    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>LogIn</title>
    <meta content='width=device-width, initial-scale=2, maximum-scale=2, user-scalable=no' name='viewport'>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SmartAdmin")

    @RenderSection("styles", required: false)

    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body class="login-page">
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_TopMenu.cshtml
<aside id="left-panel">
    <nav>
        <ul>
            <li>
                <a href="@Url.Action("Index","Home",new { area = "" }, null)" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-cogs"></i> <span class="menu-item-parent">Configuracion</span></a>
                <ul>
                    <li>
                        @Html.ActionLink("Crear Usuarios", "Index", "Usuarios", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Crear Roles", "CreateRol", "RolPermiso", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Crear Permisos", "CreatePermiso", "RolPermiso", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Crear Productos", "CrearProducto", "Producto", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Tipo Documento", "TipoDocumento", "TipoParametros", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Tipo Pago", "TipoPago", "TipoParametros", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Tipo Mascota", "TipoMascota", "TipoParametros", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Tipo Producto", "TipoProducto", "TipoParametros", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Tipo Estudio", "TipoEstudio", "TipoParametros", new { area = "" }, null)
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fas fa-paw"></i> <span class="menu-item-parent">Historia Clinica</span></a>
                <ul>
                    <li>
                        @Html.ActionLink("Crear Clientes", "Index", "Clientes", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Crear Mascotas", "IndexMascota", "Clientes", new { area = "" }, null)
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-lg fa-fw fa-shopping-cart"></i> <span class="menu-item-parent">Tienda</span></a>
                <ul>
                    <li>
                        @Html.ActionLink("Ventas", "Create", "Reporte", new { area = "" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("ConsolidadoVentas", "ReporteVentas", "Reporte", new { area = "" }, null)
                    </li>
                </ul>
            </li>
        </ul>

</nav>
</aside>