Controllers/RolPermisoController.cs
using PrVeterinaria.Libs;
using PrVeterinaria.Models;
using PrVeterinaria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WinForms;

namespace PrVeterinaria.Controllers
{
    public class RolPermisoController : Controller
    {
        DBContexto _db = new DBContexto();
        [Authentication("USUARIOS")]
        public ActionResult CreateRol()
        {
            var roles = _db.Rol.Select(rol =>
                        new Rolconsulta
                        {
                            id_rol = rol.id_rol,
                             nombreRol = rol.nombreRol
                         }).ToList();
            ViewBag.rol = roles;
            return View();
        }

        [HttpPost]
        public ActionResult CreateRol(Rolconsulta rol)
        {
            if (ModelState.IsValid)
            {
                Rol nuevoRol = new Rol();
                nuevoRol.nombreRol = rol.nombreRol.ToUpper();
                _db.Rol.Add(nuevoRol);
                _db.SaveChanges();

                return RedirectToAction("CreateRol");
            }
            else
            {
                return RedirectToAction("CreateRol");
            }
        }

        [Authentication("USUARIOS")]
        public ActionResult CreatePermiso()
        {
            var permiso = _db.Permiso.Select(p =>
                        new Permisoconsulta
                        {
                            id_permiso = p.id_permiso,
                            nombrePermiso = p.nombrePermiso
                        }).ToList();
            ViewBag.Permiso = permiso;
            return View();
        }

        [HttpPost]
        public ActionResult CreatePermiso(Permisoconsulta permiso)
        {
            if (ModelState.IsValid)
            {
                Permiso nuevoPermiso = new Permiso();
                nuevoPermiso.nombrePermiso = permiso.nombrePermiso.ToUpper();
                _db.Permiso.Add(nuevoPermiso);
                _db.SaveChanges();

                return RedirectToAction("CreatePermiso");
            }
            else
            {
                return RedirectToAction("CreatePermiso");
            }
        }


        [Authentication("USUARIOS")]
        public ActionResult detalle(int? id)
        {
            if (id == null)
            {
                Redirect("Create");
            }
            var rol = _db.Rol.Where(x => x.id_rol == id).FirstOrDefault();
            RolPermiso rolpermiso = new RolPermiso();
            rolpermiso.id_rol = rol.id_rol;
            rolpermiso.nombreRol = rol.nombreRol;
           
            ViewBag.Permisos = new SelectList(_db.Permiso, "id_permiso", "nombrePermiso");
            var PermisoRol = _db.PermisoRol.Where(x => x.id_rol == id).ToList();

            var consulta = (from pr in _db.PermisoRol
                            join r in _db.Rol on pr.id_rol equals r.id_rol
                            join p in _db.Permiso on pr.id_permiso equals p.id_permiso
                            where  pr.id_rol==id
                            select new RolPermiso
                            {
                                id_permiso=p.id_permiso,
                                nombrePermiso= p.nombrePermiso
                            }).ToList();

            ViewBag.consulta = consulta;
            return View(rolpermiso);
        }

        [HttpPost]
        public ActionResult detalle(RolPermiso rolpermiso)
        {
            PermisoRol permisoRol = new PermisoRol();
            permisoRol.id_rol = rolpermiso.id_rol;
            permisoRol.id_permiso = rolpermiso.id_permiso;

            _db.PermisoRol.Add(permisoRol);
            _db.SaveChanges();

            return RedirectToAction("Detalle", new { id = rolpermiso.id_rol });

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Views/RolPermiso/CreatePermiso.cshtml
@model  PrVeterinaria.Models.ViewModel.Permisoconsulta
@{
    ViewBag.Title = "Rol";
}
@section Styles {
    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")

}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">
            <header role="heading" class="ui-sortable-handle">
                <h2>Lista de Permisos</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table class="table table-bordered table-striped" id="tlbItem">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.Permiso != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.Permisoconsulta>)ViewBag.Permiso)
                                    {
                                        <tr>
                                            <td align="center">@item.id_permiso                  </td>
                                            <td align="center">@item.nombrePermiso               </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("CreatePermiso", "RolPermiso",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Agregar Permiso</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.nombrePermiso, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.nombrePermiso, "", new { @class = "text-danger" })
                        </div>                     
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts

{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")

    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#tlbItem').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}

Views/RolPermiso/CreateRol.cshtml
@model  PrVeterinaria.Models.ViewModel.Rolconsulta
@{
    ViewBag.Title = "Rol";
}
@section Styles {

    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")


}


<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">

            <header role="heading" class="ui-sortable-handle">
                <h2>Lista de Roles</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table id="example" class="table table-striped table-bordered dataTable" style="width: 100%;" role="grid" aria-describedby="example_info">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                    <th> </th>

                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.rol != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.Rolconsulta>)ViewBag.rol)
                                    {
                                        <tr>
                                            <td align="center">@item.id_rol                    </td>
                                            <td align="center">@item.nombreRol               </td>
                                            <td>
                                                @Html.ActionLink("Detalle", "Detalle", new { id = item.id_rol })
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>

                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("CreateRol", "RolPermiso",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Agregar Rol</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.nombreRol, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.nombreRol, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts
{

    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")



    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#example').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}

Views/RolPermiso/Detalle.cshtml
@model  PrVeterinaria.Models.ViewModel.RolPermiso

@{
    ViewBag.Title = "Permisos de Rol";
}
@section Styles {

    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")


}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">

            <header role="heading" class="ui-sortable-handle">
                <h2> Lista de Permisos por Rol </h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                    <a href="@Url.Action("CreateRol","RolPermiso")" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-reply"></i> Volver
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table id="example" class="table table-striped table-bordered dataTable" style="width: 100%;" role="grid" aria-describedby="example_info">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>


                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.consulta != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.RolPermiso>)ViewBag.consulta)
                                    {
                                        <tr>
                                            <td align="center">@item.id_permiso   </td>
                                            <td align="center">@item.nombrePermiso</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("Detalle", "RolPermiso",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Ingresar Grado de Escolaridad</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("id", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.id_rol, new { htmlAttributes = new { @class = "form-control text-uppercase", @id = "fechaIngreso", @readonly = "true" } })
                            @Html.ValidationMessageFor(model => model.id_rol, "", new { @class = "text-danger" })
                        </div>
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(Model => Model.nombreRol, new { htmlAttributes = new { @class = "form-control", id = "unidad", @readonly = "true" } })
                            @Html.ValidationMessageFor(model => model.nombreRol, "", new { @class = "text-danger" })
                        </div>
                        @Html.Label("Permiso", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.DropDownListFor(model => model.id_permiso, (IEnumerable<SelectListItem>)ViewBag.Permisos, "-- Seleccione --", htmlAttributes: new { @class = "form-control", id = "idItem" })
                            @Html.ValidationMessageFor(model => model.id_permiso, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardarItem" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>



@section Scripts
{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")


    <script>

           $("#btnGuardarInfo").prop('disabled', true)

        $("#idpermisoRol").change(function ()
        {
            if ($("#idpermisoRol").val().length)
            {
                $("#btnGuardarInfo").prop('disabled', false)
            }
            else
            {
                $("#btnGuardarInfo").prop('disabled', true)
            }

        })

        function Modal() {
            $("#modalCrear").show()
        }

         function muestraMensaje()
         {
             var url= '@Url.Action("Detalle", "RolPermiso")';
             window.location.href = url;
         }

           $(document).ready(function () {
               $('#example').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}