Models/TipoDocumento.cs
namespace PrVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TipoDocumento")]
    public partial class TipoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDocumento()
        {
            Clientes = new HashSet<Clientes>();
            Usuarios = new HashSet<Usuarios>();
        }

        [Key]
        public int id_tipoDocumento { get; set; }

        [StringLength(10)]
        public string descripcion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}

Models/TipoEstudio.cs
namespace PrVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TipoEstudio")]
    public partial class TipoEstudio
    {

        public TipoEstudio()
        {
            detalleUsuario = new HashSet<detalleUsuario>();        
        }

        [Key]
        public int id_tipoEstudio { get; set; }

        [StringLength(100)]
        public string NombreTipo { get; set; }

        public virtual ICollection<detalleUsuario> detalleUsuario { get; set; }
    }
}

Models/TipoMascota.cs
namespace PrVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TipoMascota")]
    public partial class TipoMascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoMascota()
        {
            Mascota = new HashSet<Mascota>();
        }

        [Key]
        public int id_tipoMascota { get; set; }

        [StringLength(20)]
        public string nombre { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mascota> Mascota { get; set; }
    }
}

Models/TipoPago.cs
namespace PrVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TipoPago")]
    public partial class TipoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoPago()
        {
            Factura = new HashSet<Factura>();
        }

        [Key]
        public int id_tipoPago { get; set; }

        [StringLength(100)]
        public string nombre { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}

Models/TipoProducto.cs
namespace PrVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TipoProducto")]
    public partial class TipoProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoProducto()
        {
            Producto = new HashSet<Producto>();
        }

        [Key]
        public int id_tipoProducto { get; set; }

        [StringLength(25)]
        public string descripcion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}

Controllers/TipoParametrosController.cs
using PrVeterinaria.Libs;
using PrVeterinaria.Models;
using PrVeterinaria.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WinForms;

namespace PrVeterinaria.Controllers
{
    public class TipoParametrosController : Controller
    {
        DBContexto _db = new DBContexto();
        // GET: TipoParametros
        [Authentication("USUARIOS")]
        public ActionResult TipoDocumento()
        {
            var tipoDocumento = _db.TipoDocumento.Select(p =>
                        new TipoDocumentoDTO
                        {
                            id_tipoDocumento = p.id_tipoDocumento,
                            descripcion = p.descripcion
                        }).ToList();
            ViewBag.TipoDoc = tipoDocumento;
            return View();
        }

        [HttpPost]
        public ActionResult TipoDocumento(TipoDocumentoDTO tipoDocumento)
        {
            if (ModelState.IsValid)
            {
                TipoDocumento nuevoTipo = new TipoDocumento();
                nuevoTipo.descripcion = tipoDocumento.descripcion.ToUpper();
                _db.TipoDocumento.Add(nuevoTipo);
                _db.SaveChanges();

                return RedirectToAction("TipoDocumento");
            }
            else
            {
                return RedirectToAction("TipoDocumento");
            }

        }

        [Authentication("USUARIOS")]
        public ActionResult TipoPago()
        {
            var tipoPago = _db.TipoPago.Select(p =>
                       new TipoPagoDTO
                       {
                           id_tipoPago = p.id_tipoPago,
                           nombre = p.nombre
                       }).ToList();
            ViewBag.TipoPag = tipoPago;
            return View();
        }

        [HttpPost]
        public ActionResult TipoPago(TipoPagoDTO tipoPago)
        {
            if (ModelState.IsValid)
            {
                TipoPago nuevoTipo = new TipoPago();
                nuevoTipo.nombre = tipoPago.nombre.ToUpper();
                _db.TipoPago.Add(nuevoTipo);
                _db.SaveChanges();

                return RedirectToAction("TipoPago");
            }
            else
            {
                return RedirectToAction("TipoPago");
            }

        }

        [Authentication("CLIENTES")]
        public ActionResult TipoMascota()
        {
            var tipoMascota = _db.TipoMascota.Select(p =>
                       new TipoMascotaDTO
                       {
                           id_tipoMascota = p.id_tipoMascota,
                           nombre = p.nombre
                       }).ToList();
            ViewBag.TipoMas = tipoMascota;
            return View();
        }

        [HttpPost]
        public ActionResult TipoMascota(TipoMascotaDTO tipoMascota)
        {
            if (ModelState.IsValid)
            {
                TipoMascota nuevoTipo = new TipoMascota();
                nuevoTipo.nombre = tipoMascota.nombre.ToUpper();
                _db.TipoMascota.Add(nuevoTipo);
                _db.SaveChanges();

                return RedirectToAction("TipoMascota");
            }
            else
            {
                return RedirectToAction("TipoMascota");
            }

        }

        [Authentication("VENTAS")]
        public ActionResult TipoProducto()
        {
            var tipoProducto = _db.TipoProducto.Select(p =>
                       new TipoProductoDTO
                       {
                           id_tipoProducto = p.id_tipoProducto,
                           descripcion = p.descripcion
                       }).ToList();
            ViewBag.TipoProduc = tipoProducto;
            return View();
        }

        [HttpPost]
        public ActionResult TipoProducto(TipoProductoDTO tipoProducto)
        {
            if (ModelState.IsValid)
            {
                TipoProducto nuevoTipo = new TipoProducto();
                nuevoTipo.descripcion = tipoProducto.descripcion.ToUpper();
                _db.TipoProducto.Add(nuevoTipo);
                _db.SaveChanges();

                return RedirectToAction("TipoProducto");
            }
            else
            {
                return RedirectToAction("TipoProducto");
            }

        }

        [Authentication("USUARIOS")]
        public ActionResult TipoEstudio()
        {
            var tipoEstudio = _db.TipoEstudio.Select(p =>
                       new TipoEstudioDTO
                       {
                           id_tipoEstudio = p.id_tipoEstudio,
                           NombreTipo = p.NombreTipo
                       }).ToList();
            ViewBag.TipoEstu = tipoEstudio;
            return View();
        }

        [HttpPost]
        public ActionResult TipoEstudio(TipoEstudioDTO tipoEstudio)
        {
            if (ModelState.IsValid)
            {
                TipoEstudio nuevoTipo = new TipoEstudio();
                nuevoTipo.NombreTipo = tipoEstudio.NombreTipo.ToUpper();
                _db.TipoEstudio.Add(nuevoTipo);
                _db.SaveChanges();

                return RedirectToAction("TipoEstudio");
            }
            else
            {
                return RedirectToAction("TipoEstudio");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TipoParametros/TipoDocumento.cshtml
@model  PrVeterinaria.Models.ViewModel.TipoDocumentoDTO
@{
    ViewBag.Title = "Rol";
}
@section Styles {
    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")

}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">
            <header role="heading" class="ui-sortable-handle">
                <h2>Tipo Documento</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table class="table table-bordered table-striped" id="tlbItem">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.TipoDoc != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.TipoDocumentoDTO>)ViewBag.TipoDoc)
                                    {
                                        <tr>
                                            <td align="center">@item.id_tipoDocumento                  </td>
                                            <td align="center">@item.descripcion               </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("TipoDocumento", "TipoParametros",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Ingresar Tipo de Documento</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts

{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")

    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#tlbItem').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}

Views/TipoParametros/TipoEstudio.cshtml
@model  PrVeterinaria.Models.ViewModel.TipoEstudioDTO
@{
    ViewBag.Title = "Rol";
}
@section Styles {
    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")

}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">
            <header role="heading" class="ui-sortable-handle">
                <h2>Grados de Escolaridad</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table class="table table-bordered table-striped" id="tlbItem">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.TipoEstu != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.TipoEstudioDTO>)ViewBag.TipoEstu)
                                    {
                                        <tr>
                                            <td align="center">@item.id_tipoEstudio                  </td>
                                            <td align="center">@item.NombreTipo               </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("TipoEstudio", "TipoParametros",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Ingresar Grado de Escolaridad</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.NombreTipo, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.NombreTipo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts

{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")

    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#tlbItem').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}

Views/TipoParametros/TipoMascota.cshtml
@model  PrVeterinaria.Models.ViewModel.TipoMascotaDTO
@{
    ViewBag.Title = "Rol";
}
@section Styles {
    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")

}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">
            <header role="heading" class="ui-sortable-handle">
                <h2>Lista de Especies Animales</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table class="table table-bordered table-striped" id="tlbItem">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.TipoMas != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.TipoMascotaDTO>)ViewBag.TipoMas)
                                    {
                                        <tr>
                                            <td align="center">@item.id_tipoMascota                  </td>
                                            <td align="center">@item.nombre               </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("TipoMascota", "TipoParametros",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Ingresar Especie Animal</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts

{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")

    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#tlbItem').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}

Views/TipoParametros/TipoPago.cshtml
@model  PrVeterinaria.Models.ViewModel.TipoPagoDTO
@{
    ViewBag.Title = "Rol";
}
@section Styles {
    @Styles.Render("~/Content/DataTables/dataTables.bootstrap4.min.css")

}

<section>
    <div id="content">
        <div class="jarviswidget jarviswidget-color-white jarviswidget-sortable" id="wid-id-0" data-widget-editbutton="false" role="widget" style="position: relative; opacity: 1; left: 0px; top: 0px;">
            <header role="heading" class="ui-sortable-handle">
                <h2>Tipo Pago</h2>
                <div class="jarviswidget-ctrls" role="menu">
                    <a href="#" data-toggle="modal" data-target="#modalDetalles" class="button-icon jarviswidget-edit-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Nuevo">
                        <div class="btn">
                            <i class="fa fa-plus"></i> Nuevo
                        </div>
                    </a>
                </div>
            </header>
            <div class="widget-body">
                <div class="row galeria">
                    <div class="col-md-12">
                        <table class="table table-bordered table-striped" id="tlbItem">
                            <thead>
                                <tr>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> ID                        </th>
                                    <th> <p style="text-align:center;font-family:Arial;font-size:90%"> Nombre                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (ViewBag.TipoPag != null)

                                {
                                    foreach (var item in (List<PrVeterinaria.Models.ViewModel.TipoPagoDTO>)ViewBag.TipoPag)
                                    {
                                        <tr>
                                            <td align="center">@item.id_tipoPago                 </td>
                                            <td align="center">@item.nombre               </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="modalDetalles">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Ajax.BeginForm("TipoPago", "TipoParametros",
       new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "Div-Kit"
       }))
            {
                <div class="modal-header bg-color-blueDark txt-color-white">
                    <h4 class="modal-title">Ingresar Tipo de Pago</h4>
                    <button type="button" class="close txt-color-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5 text-align-left">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control text-uppercase", @id="nombre" } })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-pull-6 form-group col-md-2 text-align-center">
                    <input type="submit" id="btnGuardar" value="Guardar" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>

@section Scripts

{
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.bootstrap4.min.js")
    @Scripts.Render("~/Scripts/i18n/jquery.dataTables.es.js")

    <script>

        $("#btnGuardar").prop('disabled', true)

        $("#nombre").change(function () {
            if ($("#nombre").val().length > 0) {
                $("#btnGuardar").prop('disabled', false)
            }
            else {
                $("#btnGuardar").prop('disabled', true)
            }

        })

        $(document).ready(function () {
            $('#tlbItem').DataTable({

                "oLanguage": {
                    "oPaginate": {
                        "sFirst": sFirst,
                        "sLast": sLast,
                        "sNext": sNext,
                        "sPrevious": sPrevious,
                    },

                    "sEmptyTable": sEmptyTable,
                    "sInfo": sInfo,
                    "sInfoEmpty": sInfoEmpty,
                    "sInfoFiltered": sInfoFiltered,
                    "sZeroRecords": sZeroRecords,
                    "sLengthMenu": sLengthMenu
                },
                "order": [0, "desc"],
            });
        });
    </script>
}